// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPRUhizYtTjmNjIqE0N0dSQLP1942Va8',
    appId: '1:137177383131:web:05317106c9dfbcd3328cfe',
    messagingSenderId: '137177383131',
    projectId: 'asl-attara',
    authDomain: 'asl-attara.firebaseapp.com',
    storageBucket: 'asl-attara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkfA6CfPA2EyPTqJZTdth80eNXU6q_8E',
    appId: '1:137177383131:android:17c88f6e34766bb4328cfe',
    messagingSenderId: '137177383131',
    projectId: 'asl-attara',
    storageBucket: 'asl-attara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT54mW8ttsupS86AK2jbK685RV5FCEtRk',
    appId: '1:137177383131:ios:ddfb2276f929606d328cfe',
    messagingSenderId: '137177383131',
    projectId: 'asl-attara',
    storageBucket: 'asl-attara.firebasestorage.app',
    iosBundleId: 'com.example.aslattara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT54mW8ttsupS86AK2jbK685RV5FCEtRk',
    appId: '1:137177383131:ios:ddfb2276f929606d328cfe',
    messagingSenderId: '137177383131',
    projectId: 'asl-attara',
    storageBucket: 'asl-attara.firebasestorage.app',
    iosBundleId: 'com.example.aslattara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOPRUhizYtTjmNjIqE0N0dSQLP1942Va8',
    appId: '1:137177383131:web:0e878a9bdb6f3cab328cfe',
    messagingSenderId: '137177383131',
    projectId: 'asl-attara',
    authDomain: 'asl-attara.firebaseapp.com',
    storageBucket: 'asl-attara.firebasestorage.app',
  );
}
